### ISSUE TITLE
There are some error when search  on the DataHub Web

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1942] opened 2020-10-15 08:03 UTC
Hi , There are some error when I search  on the DataHub Web, As shown below：
06:37:57.704 [qtp626202354-13] INFO  c.l.parseq.TaskDescriptorFactory - No provider found for TaskDescriptor, falling back to DefaultTaskDescriptor
06:38:01.473 [qtp626202354-16] ERROR c.l.metadata.dao.browse.ESBrowseDAO - Browse query failed: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
06:38:24.197 [qtp626202354-9] ERROR c.l.metadata.dao.search.ESSearchDAO - Search query failed:Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]

Hi,How can I solve this problem ?

**Comment by mars-lan** [comment] 2020-10-16 11:52
Seems like a duplicate of https://github.com/linkedin/datahub/issues/1943. Feel free to reopen if it's not.

**Closed by mars-lan** 2020-10-16 11:52 UTC
Labels: question
