### ISSUE TITLE
Handle unknown user URNs gracefully

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1577] opened 2020-02-28 15:44 UTC
**Is your feature request related to a problem? Please describe.**
If a user cannot be retrieved from the database (might be an owner, in an audit record or somewhere else), the UI displays an error. This is hard to debug because the page doesn't show any useful information.

This case occurs because the architecture puts the onus on either the rest client or the MCE job to validate relationships. It is hard to do this in a rest client because various jobs are dealing with collecting data from disparate parts of the system. How does a database crawler verify that all users that are table owners or have access permissions are already in DataHub. 

MCE could validate every entity and create any missing ones, but that would be a performance hit. MCE currently validates some users and rejects dataset changes if the user is not found.

**Describe the solution you'd like**
When we know the user that we are looking for, return a dummy user that populates the URN and possibly sets the display name to something like "URN (unknown)". That would at least let users see the id of the owners, but also that additional information is missing. That would When the user record is created, those details will be resolved.

**Describe alternatives you've considered**
As mentioned above, have the MCE jobs detect that users are missing and create the user record.

Another option would be to force the rest clients to guarantee all user entities are created before sending other data types. Forcing every rest client to have perfect knowledge of all users and datasets seems like it would require all collected data to be staged before sending to DataHub. That greatly reduces the value of the kafka message bus and consumers.

**Additional context**

**Comment by mars-lan** [comment] 2020-03-08 14:33
This is an excellent question and showed that you have gained deep understanding of the architecture. You're completely correct that MCE is free to contain "dangling URN" for entities that yet to have any aspect stored in GMS. This is indeed by design to support asynchronous collection of metadata from different sources and would be difficult, or undesirable, to change.

The key issue here is the behavior of a `GET` to GMS for an entity that contains no aspect. By default it returns `404 Not Found` which means the client will need to handle the exception accordingly. One options it to provide a "get or set/return default" style of API as suggested. Another is to just handle this in UI in a more graceful manner. What's your thoughts here @theseyi ?

**Comment by theseyi** [comment] 2020-03-09 17:09
In the client app we can definitely improve handling of 404s so it's clear that this metadata is missing. @ben5448 Can you provide a few instances, so we have a bit more context and appreciation of the problem from your perspective? Thanks for reporting

**Comment by ben5448** [comment] 2020-03-09 23:58
The issue you are describing is a different problem. I am seeing a 500 "internal server error" with a message about a null reference. The root cause sounds very similar.

In my case the set of corporate users come from an LDAP directory where we have usernames, display names and email addresses. Datasets have multiple owner relationships associated based on database grants, file/group ownership and jobs that create the datasets. In some cases these dataset owners are not in LDAP because they are service accounts or users that were purged from the system.

When the dataset is created, these dataset owners do not match any corporate users in the MySQL database. When the website requests the set of owners for the dataset, the frontend returns a 500 internal server error and a message about referencing a null pointer. None of the owners are returned. The web page displays an error with an option to retry. The user has no idea how many users, if any, are associated with the dataset much less the id (urn) of those users.

As mentioned, there are multiple ways to solve this problem. I prefer isolating the issue to the back end (GMS or MCE) so the problem is transparently handled without having to reimplement in every collection script. My preference would be to return the urn or account to the web user so they can see which accounts are associated with the dataset. This provides the web user as much information as possible. (If GMS detected an unknown user, it could autocreate an entry for that user in the database, but if handled consistently that is not necessary and could slow web performance.)

Other options are for MCE to detect new corporate users if they do not exist (slows kafka consumption) or provide a "create if not existing" semantic for rest dataset clients to always pass in dummy users while preventing these dummy users from overwriting records that contain detailed information.

**Comment by mars-lan** [comment] 2020-03-11 14:18
I see. 500 definitely sounds wrong to me. Could you include the stacktrace so we can debug it further? The endpoint should return 404 in the case of dangling URN reference, which then the UI can handle correctly.

**Comment by ben5448** [comment] 2020-03-11 15:01
The request is: http://10.10.4.67:9001/api/v2/datasets/urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)/owners

Response: {"msg":"java.lang.NullPointerException"}

Stack trace:
14:59:04 [application-akka.actor.default-dispatcher-456] ERROR application - Fetch owners fail
java.lang.NullPointerException: null
	at com.linkedin.datahub.util.OwnerUtil.toWhOwner(OwnerUtil.java:30)
	at com.linkedin.datahub.dao.view.OwnerViewDao.lambda$fillDatasetOwner$0(OwnerViewDao.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.linkedin.datahub.dao.view.OwnerViewDao.fillDatasetOwner(OwnerViewDao.java:59)
	at com.linkedin.datahub.dao.view.OwnerViewDao.getDatasetOwners(OwnerViewDao.java:45)
	at controllers.api.v2.Dataset.getDatasetOwners(Dataset.java:146)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$23$$anonfun$apply$23.apply(Routes.scala:838)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$23$$anonfun$apply$23.apply(Routes.scala:838)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.mvc.Security$AuthenticatedAction.call(Security.java:69)
	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at play.core.j.JavaAction.apply(JavaAction.scala:138)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:96)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:89)
	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:192)
	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:174)
	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:170)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
	at play.core.server.AkkaHttpServer$$anonfun$14.apply(AkkaHttpServer.scala:357)
	at play.core.server.AkkaHttpServer$$anonfun$14.apply(AkkaHttpServer.scala:355)
	at akka.http.scaladsl.util.FastFuture$.akka$http$scaladsl$util$FastFuture$$strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:51)
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:50)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mars-lan** [comment] 2020-03-11 16:31
Got it. Looks like it's the mid-tier, rather than GMS, that's crapping out. @keremsahin1 could you take a look at this?

**Comment by keremsahin1** [comment] 2020-03-11 21:25
@ben5448 Thanks for the error log, it helps a lot. Seems like mid-tier code doesn't handle optional fields in the Pegasus schema. I will send a fix for this.

**Comment by keremsahin1** [comment] 2020-03-11 21:58
Pushed a fix: https://github.com/linkedin/datahub/commit/fba5cd8c5e40309fe435f6cb10db525b3f23426b

Please confirm it that's fixing your issue.

**Comment by ben5448** [comment] 2020-03-12 20:01
That resolves the issue. The ownership pages now shows the user urn with an "inactive" banner beside it. That is much better. Thank you!

**Closed** 2020-03-12 20:01 UTC
Labels: bug
