### ISSUE TITLE
Installtation issue in master branch with adding the docker-compose-ember.yml from elastic search

### ISSUE THREAD

**Issue by resulraveendran** [linkedin/datahub#3566] opened 2021-11-12 09:37 UTC
When trying to install from master branch with adding the docker-compose-ember.yml file we got an application running in 9002 port but  nothing is running in 9001. and in logs, we got this error also ""Caused by: java.net.UnknownHostException: datahub-gms""(docker logs datahub-frontend-react --tail 100 -f)

**Comment by dexter-mh-lee** [comment] 2021-11-15 21:03
Assuming this is a duplicate of https://github.com/linkedin/datahub/issues/3565 Let's consolidate into one.

**Comment by shirshanka** [comment] 2021-12-15 02:05
closing as there has been no activity on this one

**Closed by shirshanka** 2021-12-15 02:05 UTC
