### ISSUE TITLE
Though datahub-gms is started, not running

### ISSUE THREAD

**Issue by yelim-0** [linkedin/datahub#2969] opened 2021-07-28 06:40 UTC
**Describe the bug**
I ​ran the command "datahub docker quickstart".
Right after the installation of DataHub, it works well.
But it made an error with "Unable to run quickstart - the following issues were detected: \n - datahub-gms is not running" after ingesting some data.
(in my case, i ingested "bootstrap_mce.json" through the "file_to_datahub.yml" file.
each located at **/datahub/metadata-ingestion/examples/mce_files** and **_/datahub/metadata-ingestion/examples/recipes_**. also it was done successfully with the comment "pipeline finished successfully".)

I tried same thing in several times after running command "datahub docker nuke", but the result was same. 
Does anyone know the reason?

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/59372607/127275332-fdaf2864-c69a-4886-8a95-e52e5423bd3c.png)

**Desktop** 
I use docker on ubuntu 20.04 through AWS ec2.
DataHub CLI version: 0.8.6.3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]

thank you in advance.

**Comment by Muralidharanprabhakaran** [comment] 2021-08-04 06:44
I am also facing the same issue while using datahub docker quickstart. But then I tried using the docker-compose.yml file and modified the port used by gms service from 8080 to 8060 and after issuing the command  datahub docker quickstart --quickstart-compose-file docker-compose.quickstart.yml. I am getting the message "- datahub-gms is running but not healthy". All the services were working fine from last one month at start but gms service used to stop in between after having some interactions with the UI. But now the gms services is not at all working.

**Comment by Light310** [comment] 2021-08-06 07:52
Hello, I've had the same issue, you can check latest comments in this thread : #2791
Fixing memory limits for datahub-gms container helped me.

**Comment by jjoyce0510** [comment] 2021-08-16 17:50
Hi there @Muralidharanprabhakaran & @yelim-0!

This was a known regression in the GMS container due to fixed memory constraints that were too conservatively placed. Version 0.8.9 https://github.com/linkedin/datahub/releases should be fixed on this front!

Please try it out and let me know if it works.

Thanks
John

**Comment by jjoyce0510** [comment] 2021-10-04 17:54
@shirshanka lets close this issue!

**Closed** 2022-01-25 17:49 UTC
Labels: question

**Comment by yiyuanbb** [comment] 2022-08-03 07:25
I'm also facing the same issue,but fixed memory limits for datahub-gms container can't helped me @Light310

**Comment by Intoxinator** [comment] 2022-08-24 03:18
I'm getting the same issue - however I don't think that it's memory related. The container settings show 1g for stack and heap. Instead, I'm getting:

ERROR: No such classes directory file:///etc/datahub/plugins/auth/resources

The only thing that *may* contribute to this (outside of the instructions in the quickstart) is that I'm using pyenv and virtualenv for the environment that datahub is setup in... I wonder if it's fine at the download/config stage, but when it gets to running it Docker, the environment is running under the system python (3.10 for me defined by my global pyenv settings) rather than the virtualenv...

**Comment by mohdsiddique** [comment] 2022-08-24 05:22
> I'm getting the same issue - however I don't think that it's memory related. The container settings show 1g for stack and heap. Instead, I'm getting:
> 
> ERROR: No such classes directory file:///etc/datahub/plugins/auth/resources
> 
> The only thing that _may_ contribute to this (outside of the instructions in the quickstart) is that I'm using pyenv and virtualenv for the environment that datahub is setup in... I wonder if it's fine at the download/config stage, but when it gets to running it Docker, the environment is running under the system python (3.10 for me defined by my global pyenv settings) rather than the virtualenv...

The fix is for the issue **ERROR: No such classes directory file:///etc/datahub/plugins/auth/resources**  available in quickstart/docker-compose.quickstart.yml.

if you are using *docker-compose-without-neo4j-m1.quickstart.yml* for quickstart then as quick fix, you can add the below statement in docker-compose-without-neo4j-m1.quickstart.yml after line number 88

`- ${HOME}/.datahub/plugins/auth/resources/:/etc/datahub/plugins/auth/resources`

**Comment by Intoxinator** [comment] 2022-08-24 06:15
For anybody else bumping into this thread that is looker for the docker-compose yml, you can find it here: https://datahubproject.io/docs/quickstart#customization

Thanks for the quick response - that's fixed my issue.
