### ISSUE TITLE
Dependencies issue with certifi in acryl-datahub 0.8.1.2

### ISSUE THREAD

**Issue by remisalmon** [linkedin/datahub#2717] opened 2021-06-18 16:19 UTC
**Describe the bug**
The `certifi` package version is not correctly resolved when installing the acryl-datahub Snowflake ingestion module with version  0.8.1.2:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
snowflake-connector-python 2.4.5 requires certifi<2021.0.0, but you have certifi 2021.5.30 which is incompatible.
```

**To Reproduce**
1. Create a new python virtual env
2. `pip install -U pip setuptools`
3. `pip install acryl-datahub[snowflake]==0.8.1.2` (the error above shows up)
4. Snowflake ingestion is broken because the wrong version of `certifi` gets installed

**Expected behavior**
The correct version of certifi `certifi<2021.0.0` should get installed.

**Desktop (please complete the following information):**
 - OS: MacOS, Python 3.8

**Comment by hsheth2** [comment] 2021-06-18 16:56
Interestingly, I can reproduce with Python 3.8 but cannot reproduce with Python 3.6. I'm also on MacOS.

Additionally, if I manually run `pip install --upgrade 'certifi<2021.0.0'` before installing with `pip install 'acryl-datahub[snowflake]==0.8.1.2'`, it seems to work.

Not quite sure what's going on here, but I'm continuing to look into it.

**Comment by hsheth2** [comment] 2021-06-18 17:16
@remisalmon can you try running `pip install --upgrade 'acryl-datahub[snowflake]==0.8.1.2'`?

I believe the `--upgrade` flag also gives pip the permission to downgrade packages if needed, which is what's necessary here.

Still don't know why it doesn't resolve the dependencies correctly on the first pass.

**Comment by remisalmon** [comment] 2021-06-18 19:55
The upgrade flag fixed the issue, not sure why either. Thanks @hsheth2!

**Comment by hsheth2** [comment] 2021-06-25 17:42
@remisalmon wanted to follow up here: seems like you discovered a bug in pip, which will be fixed by https://github.com/pypa/pip/pull/10083. @uranusjr did some outstanding debugging work, which is documented in the comments of https://github.com/pypa/pip/issues/10081.

**Comment by shirshanka** [comment] 2021-06-25 19:17
Closing as this was fixed in pip.

**Closed by shirshanka** 2021-06-25 19:17 UTC
Labels: bug
