### ISSUE TITLE
Which runing steps did I miss  About Metadata Ingestion

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1961] opened 2020-10-26 09:53 UTC
I follow the description of the page “ https://github.com/linkedin/datahub/tree/master/metadata-ingestion”

**1 ： ./gradlew :metadata-events:mxe-schemas:build**

**2：[root@localhost kafka-etl]# docker ps**
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS   PORTS                                                      NAMES
31ae7002a99a        linkedin/datahub-mce-consumer:v0.4.3                  "/bin/sh -c /datahub…"   7 days ago          Up 7 days   0.0.0.0:9090->9090/tcp                                     datahub-mce-consumer
c6f727068322        linkedin/datahub-frontend:v0.4.3                      "datahub-frontend/bi…"   7 days ago          Up 7 days   0.0.0.0:9001->9001/tcp                                     datahub-frontend
2dccdaa779dd        landoop/kafka-topics-ui:0.9.4                         "/run.sh"                7 days ago          Up 7 days   0.0.0.0:18000->8000/tcp                                    kafka-topics-ui
c98a266b184c        linkedin/datahub-mae-consumer:v0.4.3                  "/bin/sh -c /datahub…"   7 days ago          Up 7 days   9090/tcp, 0.0.0.0:9091->9091/tcp                           datahub-mae-consumer
a452bc971f64        linkedin/datahub-gms:v0.4.3                           "/bin/sh -c /datahub…"   7 days ago          Up 7 days   0.0.0.0:8080->8080/tcp                                     datahub-gms
6cd4da7466c1        confluentinc/cp-kafka-rest:5.4.0                      "/etc/confluent/dock…"   7 days ago          Up 7 days   0.0.0.0:8082->8082/tcp                                     kafka-rest-proxy
b5d1fc02a43b        landoop/schema-registry-ui:latest                     "/run.sh"                7 days ago          Up 7 days   0.0.0.0:8000->8000/tcp                                     schema-registry-ui
c35c27b656c9        confluentinc/cp-schema-registry:5.4.0                 "/etc/confluent/dock…"   7 days ago          Up 7 days   0.0.0.0:8081->8081/tcp                                     schema-registry
b20dc35da9cb        docker.elastic.co/kibana/kibana:5.6.8                 "/bin/bash /usr/loca…"   7 days ago          Up 7 days   0.0.0.0:5601->5601/tcp                                     kibana
cb7f88a3183f        confluentinc/cp-kafka:5.4.0                           "/etc/confluent/dock…"   7 days ago          Up 7 days   0.0.0.0:9092->9092/tcp, 0.0.0.0:29092->29092/tcp           broker
7300568ce02b        neo4j:3.5.7                                           "/sbin/tini -g -- /d…"   7 days ago          Up 7 days   0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   neo4j
5862d57aafe5        docker.elastic.co/elasticsearch/elasticsearch:5.6.8   "/bin/bash bin/es-do…"   7 days ago          Up 7 days   0.0.0.0:9200->9200/tcp, 9300/tcp                           elasticsearch
3257573c53bf        confluentinc/cp-zookeeper:5.4.0                       "/etc/confluent/dock…"   7 days ago          Up 7 days   2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp                 zookeeper
8cfb9c5c289f        mysql:5.7                                             "docker-entrypoint.s…"   7 days ago          Up 7 days   0.0.0.0:3306->3306/tcp, 33060/tcp                          mysql

**3.   python3 mysql_etl.py **
   XXXXXX has been successfully produced!

**then I only see the table list :**
![image](https://user-images.githubusercontent.com/72068448/97157411-04ad8e80-17b3-11eb-8592-f6fb38615c0a.png)

**but there no the table structure metadata: **
![image](https://user-images.githubusercontent.com/72068448/97157522-27d83e00-17b3-11eb-93cc-ae64599dddfb.png)

**I would like to know if I have missed the runing steps ？After executing mysql_etl.py，Does this kafka_etl.py need to be run?**

**Comment by mars-lan** [comment] 2020-10-26 12:32
This seems like a duplicate of https://github.com/linkedin/datahub/issues/1953. Let's focus the discussion there?

**Closed by mars-lan** 2020-10-26 12:32 UTC
Labels: question
