### ISSUE TITLE
 after ingest sample data, There is no content  on the DataHub Web

### ISSUE THREAD

**Issue by starsliao** [linkedin/datahub#1941] opened 2020-10-15 07:23 UTC
before run this command：docker build -t ingestion -f docker/ingestion/Dockerfile . && cd docker/ingestion && docker-compose up，
 There is no content  on the DataHub Web ，As shown in the figure below：
<img width="810" alt="linkedin_datahub1" src="https://user-images.githubusercontent.com/3349611/96089802-ebc2f480-0ef9-11eb-8ef0-d686d97a6398.png">
 after run this command ：docker build -t ingestion -f docker/ingestion/Dockerfile . && cd docker/ingestion && docker-compose up，
 There is no content  on the DataHub Web ，As shown in the figure below：
![image](https://user-images.githubusercontent.com/3349611/96090042-3fcdd900-0efa-11eb-9101-beb7cda910ae.png)

**Comment by jywadhwani** [comment] 2020-10-16 00:04
I suspect `datahub-mae-consumer` container is not running. `docker container ls` should be able to verify the same.

**Comment by HondaHsu2020** [comment] 2020-10-17 08:59
@mars-lan   
**My problem as  same as starsliao’ s problem:** 
" 07:59:28.046 [qtp626202354-17] INFO  c.l.parseq.TaskDescriptorFactory - No provider found for TaskDescriptor, falling back to DefaultTaskDescriptor
07:59:30.251 [qtp626202354-11] ERROR c.l.metadata.dao.search.ESSearchDAO - Search query failed:Elasticsearch exception **[type=search_phase_execution_exception, reason=all shards failed]**
08:23:26.522 [qtp626202354-17] ERROR c.l.metadata.dao.browse.ESBrowseDAO - Browse query failed: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
08:23:40.405 [qtp626202354-14] ERROR c.l.metadata.dao.search.ESSearchDAO - Search query failed:Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed] "

**I checked the run status of datahub services:** 
broker                 /etc/confluent/docker/run        Up      0.0.0.0:29092->29092/tcp, 0.0.0.0:9092->9092/tcp
datahub-frontend       datahub-frontend/bin/playB ...   Up      0.0.0.0:9001->9001/tcp
datahub-gms            /bin/sh -c /datahub/datahu ...   Up      0.0.0.0:8080->8080/tcp
datahub-mae-consumer   /bin/sh -c /datahub/datahu ...   Up      9090/tcp, 0.0.0.0:9091->9091/tcp
datahub-mce-consumer   /bin/sh -c /datahub/datahu ...   Up      0.0.0.0:9090->9090/tcp
elasticsearch          /bin/bash bin/es-docker          Up      0.0.0.0:9200->9200/tcp, 9300/tcp
kafka-rest-proxy       /etc/confluent/docker/run        Up      0.0.0.0:8082->8082/tcp
kafka-topics-ui        /run.sh                          Up      0.0.0.0:18000->8000/tcp
kibana                 /bin/bash /usr/local/bin/k ...   Up      0.0.0.0:5601->5601/tcp
mysql                  docker-entrypoint.sh --cha ...   Up      0.0.0.0:3306->3306/tcp, 33060/tcp
neo4j                  /sbin/tini -g -- /docker-e ...   Up      7473/tcp, 0.0.0.0:7474->7474/tcp, 0.0.0.0:7687->7687/tcp
schema-registry        /etc/confluent/docker/run        Up      0.0.0.0:8081->8081/tcp
schema-registry-ui     /run.sh                          Up      0.0.0.0:8000->8000/tcp
zookeeper              /etc/confluent/docker/run        Up      0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp

**Comment by mars-lan** [comment] 2020-10-17 11:59
As @HondaHsu2020 pointed out, this is likely a duplicate of https://github.com/linkedin/datahub/issues/1943. Let's focus the discussion in that issue. Closing this for now.

**Closed by mars-lan** 2020-10-17 11:59 UTC
Labels: pending-submitter-response, question
