### ISSUE TITLE
Timeout retrieving list of user entities

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1566] opened 2020-02-19 19:23 UTC
**Describe the bug**
My database currently contains a little over 600 users. The DataHub UI retrieves the list of all users by calling the frontend host with "http://FRONTENDHOST:9001/api/v1/party/entities". That call consistently returns an error: {"msg":"com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://GMSHOST:8080/corpUsers"}.

Using curl I verified that the URI returned in the error message (http://GMSHOST:8080/corpUsers) responds immediately to requests. Using Wireshark I observed that the actual call includes several arguments: http://GMSHOST:8080/corpUsers?count=10000&start=0. That query takes much longer to complete; about 25 seconds on my machine. I believe the frontend process is timing out waiting on the GMS function to return.

A couple of interesting observations:
- It appears the query is retrieving the list of URNs and then asking the database for each record separately. If so, this is a very expensive way to retrieve the data.
- Using curl I timed how long it took GMS to return different numbers of records. With no parameters, GMS returned 9 records (count said 10, but there were only 9 username/info/fullName tags in the list) instantly. At a limit slightly over 600, all records were returned in about 1 second. With a limit of 10,000 (the value sent from the frontend), the response consistently takes 25 seconds even though it returns the same data as the 600 user query. (Why does the API take much longer to return the same data with the only difference being the maximum limit?)

**To Reproduce**
1. Load DataHub with a large number of users. In my case 600 was enough running DataHub on a development VM. On a larger system it may take more.
2. Curl http://GMSHOST:8080/corpUsers?count=10000&start=0
3. Time the results with different counts.
4. Enable development tools in chrome or firefox.
5. Visit a datasets page.
6. Verify if the call to entities succeeds.

**Expected behavior**
The frontend service to get entities needs to return fast enough that the browser does not timeout. Since the frontend service depends on GMS to get all the users, GMS must return quickly as well. If the query to get all users cannot return fast enough, the UI needs to retrieve users in batches.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome, curl

**Additional context**
600 users sounds like a very small number for companies seeking to deploy DataHub. 

The frontend query to get employees calls the same GMS code. If a paging solution is implemented for entities, it will need to be implemented for any code using the employees API as well.

Only the first batch of records return the wrong number of entries. The simplest case is to use the arguments: "?count=1&start=0", which returns 0 records. "?count=1&start=1" returns 1 record.

**Comment by mars-lan** [comment] 2020-02-22 00:24
This was most likely legacy code from WhereHows days that we haven't got to migrating yet. Should happen soonish.

**Comment by keremsahin1** [comment] 2020-02-25 06:11
Hi @ben5448, just to let you know that we're working on a fix for this. We will soon publish the patch. 

Thanks,
Kerem

**Comment by mars-lan** [comment] 2020-02-27 14:31
@keremsahin1  I'm not sure it's the same problem given it's using ES for `GET_ALL`: https://github.com/linkedin/datahub/blob/4cc6dd92b2dcb62e18717eff6699ce95896c7ad3/metadata-restli-resource/src/main/java/com/linkedin/metadata/restli/BaseSearchableEntityResource.java#L90

**Comment by ben5448** [comment] 2020-02-27 20:21
I would have to trace the code again, but I believe the problem comes from using ES to get all user URNs that matched the filters (no filters were applied so all users matched). Then a map was used to query the database for each user.

What I didn't understand is why time seemed to scale linearly with the maximum number of users to return (default is 10,000) when there were only a little over 600 users in my database. How can it take longer to return results with the cap at 10k than at 1k? They both return the same set of 600 users. I would expect anything over over the maximum set of users to take the same time.

**Comment by mars-lan** [comment] 2020-10-05 17:41
We have likely identified the root cause of this internally. @camelliazhang is working on a fix.

**Comment by jjoyce0510** [comment] 2021-05-02 18:56
In the latest React application, we are not fetching an entire list of CorpUsers. Migrating to the React app should solve this issue.

Thanks
John

**Comment by shirshanka** [comment] 2021-05-02 19:00
Closing this since latest React application doesn't have this issue as stated by @jjoyce0510
Please re-open if you have issues with large number of users in React app.

**Closed by shirshanka** 2021-05-02 19:00 UTC
Labels: accepted, bug
