### ISSUE TITLE
Unable to emit metadata to DataHub GMS

### ISSUE THREAD

**Issue by VSMDD** [linkedin/datahub#2968] opened 2021-07-28 06:35 UTC
Startup error：The error report is shown in the figure below
vim example_to_datahub_rest.yml
![image](https://user-images.githubusercontent.com/31095506/127275302-001b7c43-f1ef-4ed2-a1a2-c0f7db00da5d.png)
![image](https://user-images.githubusercontent.com/31095506/127275094-f37f4351-94dc-42c9-954a-6fd7033c8d4c.png)

**Comment by Light310** [comment] 2021-08-10 07:50
Hello! Check if Datahub GMS container is running. I've had the same problem after it crashed.

**Comment by jjoyce0510** [comment] 2021-08-16 17:54
It seems that the container was not running. Do you can verify using `docker ps`. The issue is likely related to GMS failing to start due to fixed memory constraints that were too low. This has since been addressed in v0.8.9 of DataHub. Please try it out and let me know how goes!

Thanks
John

**Comment by jjoyce0510** [comment] 2021-10-04 17:54
@shirshanka lets close this issue!

**Closed** 2022-01-25 17:50 UTC
Labels: question
