### ISSUE TITLE
Generate documentation for Entity and API endpoints

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1888] opened 2020-09-22 14:47 UTC
Is anyway to generate documentation for entities, its aspects, aspect fields and API documentations? the benefit of being able to generate documentation helps data ingestion, and also end users if they only want to work on API endpoints. 
Just thought there must be some way to do so. 

Thanks,

**Comment by mars-lan** [comment] 2020-09-22 15:49
This is a bit dated but hopefully still works: https://github.com/linkedin/rest.li-api-hub

**Comment by mars-lan** [comment] 2020-09-23 11:20
Saw you posted on rest.li's github: https://github.com/linkedin/rest.li/issues/420

Yeah looks like the tool is probably outdated. Internally, we're discussing making DataHub the de facto tool for rest.li API endpoint documentations so stay tuned!

**Comment by evanw555** [comment] 2020-09-30 19:46
Not sure if this is sufficient, but Rest.li services support generated documentation out-of-the-box. For a service hosted at `https://domain`, go to `https://domain/restli/docs`. It's a little basic but it's there

**Comment by mars-lan** [comment] 2020-09-30 19:47
@newsummit Nice. Didn't know about this trick :)

**Comment by mars-lan** [comment] 2020-09-30 20:01
Updated the doc with this new trick: https://github.com/linkedin/datahub/blob/master/gms/README.md#api-documentation
Closing this issue for now.

**Comment by mars-lan** [comment] 2020-10-27 12:13
@evanw555 Seems like the endpoint (`/restli/docs`) is no longer working (See https://github.com/linkedin/datahub/issues/1966). Has it been moved to a different path?

**Comment by cobolbaby** [comment] 2020-11-20 03:16
Any progress on this issue?

**Comment by mars-lan** [comment] 2020-11-20 04:58
> Any progress on this issue?

The issue is "half fixed". See https://github.com/linkedin/rest.li/issues/464 for more details.

**Comment by maggiehays** [comment] 2022-01-25 02:36
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!

**Closed** 2022-01-25 02:36 UTC
Labels: feature-request
